version: '3'
services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    networks:
      - scroll-net
    volumes:
      - minio-data:/data
    environment:
      - MINIO_ROOT_USER=yourUser
      - MINIO_ROOT_PASSWORD=yourPassword
    expose:
      - 9000
      - 9090
    ports:
      - 9000:9000
      - 9090:9090
    command: server /data --console-address ":9090"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 2s
      retries: 3

  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: scroll1
    user: postgres
    secrets:
      - db_password
    expose:
      - 5432
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 5s
      timeout: 2s
      retries: 3
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - scroll-net

  api:
    build:
      context: .
      dockerfile: ./src/Api/Dockerfile
    image: scroll-api:latest
    container_name: scroll-api
    expose:
      - 80
    ports:
      - 8080:80
    networks:
      - scroll-net
    environment:
      ConnectionStrings__ScrollDb: "Host=db;Port=5432;Database=scroll1;Username=postgres;Password=yourPassword"
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80'

  web:
    build:
      context: .
      dockerfile: ./src/Web/Dockerfile
    image: scroll-web:latest
    container_name: scroll-web
    expose:
      - 80
    ports:
      - 8081:80
    networks:
      - scroll-net

volumes:
  pgdata:
    driver: local
  minio-data:
    driver: local

networks:
  scroll-net:
    driver: bridge

secrets:
  db_password:
    file: ./secrets/password.txt
