version: '3'
services:
  minio:
    image: minio/minio
    container_name: minio
    networks:
      - scroll-net
    volumes:
      - minio-data:/data
    environment:
      - MINIO_ROOT_USER=yourUser
      - MINIO_ROOT_PASSWORD=yourPassword
    ports:
      - "9000:9000"
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: yourUser
      POSTGRES_PASSWORD: yourPassword
      POSTGRES_DB: scroll1
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - scroll-net

  api:
    build:
      context: .
      dockerfile: ./src/Api/Dockerfile
    container_name: api
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__ScrollDb=Host=db;Port=5432;Database=scroll1;Username=yourUser;Password=yourPassword
    depends_on:
      - db
      - minio
    networks:
      - scroll-net

volumes:
  pgdata:
    driver: local
  minio-data:
    driver: local

networks:
  scroll-net:
    driver: bridge