version: '3'
services:
  db:
    container_name: scroll-pg
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: scrolladmin
      POSTGRES_PASSWORD: scrolladmin
      POSTGRES_DB: scroll1
    ports:
      - "5432:5432"
    volumes:
      - /Users/shakibharis/scroll/pgdata:/var/lib/postgresql/data
    networks:
      - traefik

  pgadmin:
    container_name: scroll-pg-admin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: info@shakib.io
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    volumes:
      - /Users/shakibharis/scroll/pgadmin:/var/lib/pgadmin
    networks:
      - traefik

  scroll-rest:
    build:
      context: .
      dockerfile: ./src/Scroll.Rest/Dockerfile
    ports:
      - "80:8080"
    depends_on:
      - db
    networks:
      - traefik

volumes:
  pgdata:
    # map it to /home/shakibharis/scroll/pgdata

  pgadmin:
    # map it to /home/shakibharis/scroll/pgdata

networks:
  traefik:
    external: true